name: Deploy Laravel

on:
  push:
    branches:
      - server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 202.10.37.49
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/wwwroot/lapbul.dikporabintuni.com

            git pull origin server

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan optimize
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
